#!/bin/sh
export RDBASE=`pwd`
pg_buildext installcheck `pwd`/Code/PgSQL/rdkit || EXIT=$?

case $(dpkg-architecture -qDEB_HOST_ARCH_ENDIAN) in
    big) exit 77 ;; # ignore test failure on s390x
esac

case $(dpkg-architecture -qDEB_HOST_ARCH) in
    i386) exit 77 ;; # ignore test failure on i386
esac

exit ${EXIT:-0}
