on:
  push:
    branches: [ test-build ]
  pull_request:
    branches: [ test-build ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_PARALLEL_LEVEL: 10
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
  RDKIT_VERSION: 2022_09_3
  LD_LIBRARY_PATH: /usr/local/lib
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: | 
          sudo apt-get update
          sudo apt-get install -y git-buildpackage vim git wget
          sudo apt install -y --no-install-recommends tzdata
          sudo apt-get install -y clang libclang-dev llvm cmake debhelper javahelper dh-make debmake libboost-all-dev libfreetype6-dev libc6-dev libeigen3-dev python3-numpy tzdata
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-14 1000
          sudo update-alternatives --install /usr/bin/cc  cc  /usr/bin/clang-14 1000

      - name: Load Externals
        run: |
          echo 'cd to debian pwd' $PWD
          echo $PWD "what is pwd"
          DEB_BUILD_OPTIONS=nocheck
          wget https://github.com/rdkit/rdkit/archive/Release_2022_09_3.tar.gz
          cp Release_2022_09_3.tar.gz rdkit-2022.09.3.tar.gz
          tar xzf rdkit-2022.09.3.tar.gz
          mv rdkit-Release_2022_09_3 rdkit-2022.09.3
          cd rdkit-2022.09.3
          echo $PWD "what is pwd"
          debmake -y -b',librdkit1,librdkit-dev' -e maria.dubyaga@scientist.com -f 'Maria Dubyaga'
          rm debian/librdkit*
          ls
          cp ../debian/control debian/control
          cp ../debian/compat debian/compat
          cp ../debian/rules debian/rules
          cp ../debian/source/format debian/source/format
          cp ../debian/rdkit1.install debian/rdkit1.install
          cp ../debian/rdkit-dev.install debian/rdkit-dev.install
          cp ../debian/source/include-binaries debian/source/include-binaries
          cd External/catch/
          wget https://github.com/catchorg/Catch2/archive/v2.13.8.tar.gz
          tar zxf v2.13.8.tar.gz
          mv Catch2-2.13.8 catch
          cd ../CoordGen/
          wget https://github.com/schrodinger/coordgenlibs/archive/v3.0.0.tar.gz
          tar zxf v3.0.0.tar.gz
          mv coordgenlibs-3.0.0 coordgen
          cd ../RingFamilies/
          wget https://github.com/rareylab/RingDecomposerLib/archive/v1.1.3_rdkit.tar.gz
          tar xzf v1.1.3_rdkit.tar.gz
          mv RingDecomposerLib-1.1.3_rdkit RingDecomposerLib
          cd ../CoordGen/
          wget https://github.com/schrodinger/maeparser/archive/v1.2.4.tar.gz
          tar xzf v1.2.4.tar.gz
          mv maeparser-1.2.4 maeparser
          cd ..
          wget https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz
          tar xzf v1.1.0.tar.gz
          echo 'ls External folder'
          ls 
          cd ..
          EDITOR=/bin/true dpkg-source -q --commit . externals
          debuild  --set-envvar=RDBASE=/rdkit-2022.09.3 --set-envvar=DEB_BUILD_OPTIONS=nocheck -S -j10 --source-option=--include-binaries --no-sign
          ls 
          echo 'list above'
          ls ..

      - name: CD to deb files
        run: |
          ls
          echo 'pwd after debuild' $PWD
          cd ..
          ls


      - uses: actions/upload-artifact@v3
        with:
          name: deb-packages
          path: |
            rdkit_2022.09.3-1.dsc
            rdkit_2022.09.3.orig.tar.gz
            rdkit-2022.09.3.tar.gz
            rdkit_2022.09.3-1.debian.tar.xz
