on:
  push:
    branches: [ test-build ]
  pull_request:
    branches: [ test-build ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_PARALLEL_LEVEL: 10
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
  RDKIT_VERSION: 2022_03_2
  LD_LIBRARY_PATH: /usr/local/lib
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Cache libboost
      uses: actions/cache@v3
      id: cache-libboost-others
      with:
        path: |
          "/usr/include/boost"
          "/usr/lib/x86_64-linux-gnu"
        key: libboost
    - name: Install libboost
      env:
        CACHE_HIT: ${{steps.cache-libboost-others.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --force --recursive /usr/include/boost/* /
        else
          sudo apt-get update && sudo apt-get install --yes libboost-all-dev
        fi

    - name: test libboost
      run: whereis boost