on:
  push:
    branches: [ test-build ]
  pull_request:
    branches: [ test-build ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_PARALLEL_LEVEL: 10
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
  RDKIT_VERSION: 2022_09_3
  LD_LIBRARY_PATH: /usr/local/lib
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: | 
          sudo apt-get update
          sudo apt-get install -y git-buildpackage vim git wget
          sudo apt install -y --no-install-recommends tzdata
          sudo apt-get install -y clang libclang-dev llvm cmake debhelper javahelper dh-make debmake libboost-all-dev libfreetype6-dev libc6-dev libeigen3-dev python3-numpy tzdata
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-14 1000
          sudo update-alternatives --install /usr/bin/cc  cc  /usr/bin/clang-14 1000

      - name: Load Externals
        run: |
          DEB_BUILD_OPTIONS=nocheck
          wget https://github.com/rdkit/rdkit/archive/Release_2022_09_3.tar.gz
          cp Release_2022_09_3.tar.gz rdkit-2022.09.3.tar.gz
          tar xzf rdkit-2022.09.3.tar.gz
          mv rdkit-Release_2022_09_3 rdkit-2022.09.3
          cd rdkit-2022.09.3   

      - name: Build packages
        run: |
          debmake -y -b',librdkit1,librdkit-dev' -e maria.dubyaga@scientist.com -f 'Maria Dubyaga'
          rm debian/librdkit*
          ls
          cp ../debian/control debian/control
          cp ../debian/compat debian/compat
          cp ../debian/rules debian/rules
          cp ../debian/rdkit1.install debian/rdkit1.install
          cp ../debian/rdkit-dev.install debian/rdkit-dev.install
          debuild  --set-envvar=RDBASE=/rdkit-2022.09.3 --set-envvar=DEB_BUILD_OPTIONS=nocheck -S -j10 --no-lintian --no-sign
          sudo apt-get install pbuilder debootstrap devscripts qemubuilder qemu-user-static binfmt-support -y
          sudo apt-get install debian-archive-keyring -y
          update-binfmts —display
          update-binfmts --enable qemu-aarch64
          sudo pbuilder create --distribution jammy --mirror http://ports.ubuntu.com/ubuntu-ports/   --architecture arm64
          sudo pbuilder --build --architecture arm64 rdkit_2022.09.3-1.dsc

      - name: CD to deb files
        run: |
          ls
          echo 'pwd after debuild' $PWD
          cd ..
          ls
          ls /var/cache/pbuilder/result/

      - uses: actions/upload-artifact@v3
        with:
          name: deb-packages
          path: |
            /var/cache/pbuilder/result/rdkit-dev_2022.9.3-1_arm64.deb
            /var/cache/pbuilder/result/rdkit1_2022.9.3-1_arm64.deb
            /var/cache/pbuilder/result/rdkit_2022.9.3-1_arm64.deb