on:
  push:
    branches: [ test-build ]
  pull_request:
    branches: [ test-build ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_PARALLEL_LEVEL: 10
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
  RDKIT_VERSION: 2022_09_3
  LD_LIBRARY_PATH: /usr/local/lib
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: build-debian.yml
            workflow_conclusion: success

      - name: Install build tools
        run: |
          echo $PWD "what is pwd"
          echo "what's here"
          ls
          cd deb-packages
          sudo apt-get update
          sudo apt-get install pbuilder debootstrap devscripts binfmt-support -y
          sudo apt-get install debian-archive-keyring -y
          sudo pbuilder create --distribution jammy --mirror http://ports.ubuntu.com/ubuntu-ports/
          sudo pbuilder --build rdkit_2022.09.3-1.dsc

      - uses: actions/upload-artifact@v3
        with:
          name: deb-packages
          path: |
            ls /var/cache/pbuilder/result/
            /var/cache/pbuilder/result/rdkit-dev_20220.09.3-1_arm64.deb
            /var/cache/pbuilder/result/rdkit1_2022.09.3-1_arm64.deb
            /var/cache/pbuilder/result/rdkit_2022.09.3-1_arm64.deb
