on:
  push:
    branches: [ test-build ]
  pull_request:
    branches: [ test-build ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_PARALLEL_LEVEL: 10
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
  RDKIT_VERSION: 2022_03_2
  LD_LIBRARY_PATH: /usr/local/lib
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Cache libboost-v1
      id: cache-libboost-v1
      uses: actions/cache@v3
      with:
        path: |
          /usr/include/boost
          /usr/lib/x86_64-linux-gnu/libboost**.so
          /usr/lib/x86_64-linux-gnu/libboost**.a
          /usr/share/doc/libboost-all-dev/copyright
          /usr/share/doc/libboost-all-dev/changelog.gz
        key: lib_cache

    - name: Install libboost-v1
      if: steps.cache-libboost-v1.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update && sudo apt-get install --yes libboost-all-dev
        ls /usr/include/
        ls /usr/lib/x86_64-linux-gnu/
        ls /usr/share/doc/libboost-all-dev/

    - name: test libboost-v1
      run: |
        whereis boost
        ls /usr/include
        ls /usr/lib/x86_64-linux-gnu/

#    - name: Cache libboost
#      uses: actions/cache@v3
#      id: cache-libboost-others
#      with:
#        path: "~/boost"
#        key: libboost_all
#    - name: Install libboost
#      env:
#        CACHE_HIT: ${{steps.cache-libboost-others.outputs.cache-hit}}
#      run: |
#        if [[ "$CACHE_HIT" == 'true' ]]; then
#          ls  ~/boost/usr/
#          sudo cp --force --recursive ~/boost/* /
#        else
#          sudo apt-get update && sudo apt-get install --yes libboost-all-dev
#          export LIST=$(ls /usr/lib/aarch64-linux-gnu/libboost*)
#          for i in $LIST; do  echo $i; done
#          export BOOST=$(ls /usr/include/boost)
#
#          mkdir -p ~/boost
#          sudo dpkg -L libboost-all-dev | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
#        fi
#
#    - name: test libboost
#      run: |
#        whereis boost
#        ls ~/boost
#        ls ~/boost/usr/
#        ls ~/boost/usr/share
#        ls ~/boost/usr/share/doc
#        ls ~/boost/usr/share/doc/libboost-all-dev

    - name: Cache coordgen
      uses: actions/cache@v3
      id: cache-coordgen
      with:
        path: "~/coordgen"
        key: coordgen
    - name: Install coordgen
      env:
        CACHE_HIT: ${{steps.cache-coordgen.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          ls  ~/coordgen/usr/include
          ls  ~/coordgen/usr/share
          sudo cp --force --recursive ~/coordgen/* /
        else
          sudo apt-get update && sudo apt-get install --yes libcoordgen-dev
          mkdir -p ~/coordgen
          sudo dpkg -L libcoordgen-dev | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/coordgen/
        fi

    - name: test coordgen
      run: |
        whereis coordgen
        ls
        ls ~/coordgen/usr/include
        ls ~/coordgen/usr/include/coordgen
        

    - name: Cache maeparser
      uses: actions/cache@v3
      id: cache-maeparser
      with:
        path: "~/maeparser"
        key: maeparser
    - name: Install maeparser
      env:
        CACHE_HIT: ${{steps.cache-maeparser.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          ls  ~/maeparser/usr/include
          ls  ~/maeparser/usr/
          sudo cp --force --recursive ~/maeparser/* /
        else
          sudo apt-get update && sudo apt-get install --yes libmaeparser-dev
          mkdir -p ~/maeparser
          sudo dpkg -L libmaeparser-dev | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/maeparser/
        fi

    - name: test maeparser
      run: |
        whereis maeparser
        ls
        ls ~/maeparser/usr/include
        ls ~/maeparser/usr/include/maeparser


    - name: Cache cargo
      id: cargo-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cargo
      if: steps.cargo-cache.outputs.cache-hit != 'true'
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env

    - name: test cargo
      run: whereis cargo