name: Publish custom cross images

on:
  push: {}

jobs:

  build_amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build tools
        run: sudo apt-get update; sudo apt-get install -y git-buildpackage vim git build-essential

      - name: Native debian build
        run: DEB_BUILD_OPTIONS=nocheck gbp buildpackage --git-ignore-new --git-no-pristine-tar -us -uc
#
#  build_arm64:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Install build tools
#        run: sudo apt-get update; sudo apt-get install -y git-buildpackage vim git build-essential ruby
#
#      - name: Install dependencies
#        run: sudo apt build-dep . -y
#
#      - name: Native debian build
#        run: DEB_BUILD_OPTIONS=nocheck DIST=focal ARCH=arm64 gbp --git-ignore-new --git-pbuilder --git-no-pristine-tar -us -uc
#        # DEB_BUILD_OPTIONS=nocheck DIST=focal ARCH=arm64 git-pbuilder -us -uc
#
#      - name: Check things out
#        run: ls; ls ..
