name: Publish custom cross images

on:
  push: {}


jobs:

  build_amd64:
    runs-on: ubuntu-22.04
    env:
      DIST: jammy
      ARCH: amd64
      DEB_BUILD_OPTIONS: nocheck

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build tools
        run: sudo apt-get update; sudo apt-get install -y git-buildpackage vim git build-essential sudo dh-make debhelper dh-python

      - name: Create base image
        run: git-pbuilder create

      - name: Check the diff
        run: git status; git diff

      - name: Build package
        run: gbp buildpackage --git-ignore-new --git-pbuilder --git-no-pristine-tar --git-arch=$ARCH --git-dist=$DIST -us -uc

#      - name: Write out apt installer script
#        run: |
#          echo '#!/bin/bash'            > /tmp/apt-installer
#          echo 'apt-get install -y $@' >> /tmp/apt-installer
#          chmod a+x /tmp/apt-installer
#
#      - name: Get build-depends
#        run: dpkg-checkbuilddeps
#
#      - name: Hop in to base image and install build depends
#        run: cowbuilder execute --basepath=/var/cache/pbuilder/base-focal-arm64.cow  --save-after-exec -- /tmp/apt-installer

      - name: Native debian build
        run:  git
#
#  build_arm64:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Install build tools
#        run: sudo apt-get update; sudo apt-get install -y git-buildpackage vim git build-essential ruby
#
#      - name: Install dependencies
#        run: sudo apt build-dep . -y
#
#      - name: Native debian build
#        run: DEB_BUILD_OPTIONS=nocheck DIST=focal ARCH=arm64 gbp --git-ignore-new --git-pbuilder --git-no-pristine-tar -us -uc
#        # DEB_BUILD_OPTIONS=nocheck DIST=focal ARCH=arm64 git-pbuilder -us -uc
#
#      - name: Check things out
#        run: ls; ls ..
