name: Build and publish Debian packages

on:
  push: {}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build_amd64:
    runs-on: buildjet-16vcpu-ubuntu-2204
    env:
      DIST: jammy
      ARCH: amd64
      DEB_BUILD_OPTIONS: nocheck

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build tools
        run: sudo apt-get update; sudo apt-get install -y git build-essential git-buildpackage debhelper dh-python postgresql-server-dev-all

      - name: Create base image
        run: git-pbuilder create

      - name: Remove github stuff
        run: rm -rf .github/

      - name: Build package
        run: gbp buildpackage --git-ignore-new --git-pbuilder --git-no-pristine-tar --git-arch=$ARCH --git-dist=$DIST -us -uc

      - name: Check for debs
        run: ls -alh .; ls -alh ..

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::989722935798:role/gha-rdkit-debian
          role-session-name: samplerolesession
          aws-region: eu-central-1
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          sudo apt-get install ruby awscli
          sudo gem install deb-s3
          aws sts get-caller-identity
          aws s3 ls s3://rdkit-rs-debian/
          deb-s3 upload --bucket=rdkit-rs-debian --s3-region=eu-central-1 --arch=$ARCH --codename=$DIST ../*.deb

  build_arm64:
    runs-on: buildjet-16vcpu-ubuntu-2204-arm
    env:
      DIST: jammy
      ARCH: arm64
      DEB_BUILD_OPTIONS: nocheck

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build tools
        run: sudo apt-get update; sudo apt-get install -y git build-essential git-buildpackage debhelper dh-python postgresql-server-dev-all

      - name: Create base image
        run: git-pbuilder create

      - name: Remove github stuff
        run: rm -rf .github/

      - name: Build package
        run: gbp buildpackage --git-ignore-new --git-pbuilder --git-no-pristine-tar --git-arch=$ARCH --git-dist=$DIST -us -uc

      - name: Check for debs
        run: ls -alh .; ls -alh ..

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::989722935798:role/gha-rdkit-debian
          role-session-name: samplerolesession
          aws-region: eu-central-1
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          sudo apt-get install ruby awscli
          sudo gem install deb-s3
          aws sts get-caller-identity
          aws s3 ls s3://rdkit-rs-debian/
          deb-s3 upload --bucket=rdkit-rs-debian --s3-region=eu-central-1 --arch=$ARCH --codename=$DIST ../*.deb
